kind: Deployment
apiVersion: apps/v1

metadata:
  name: notesapp-deployment
  namespace: notesapp
  labels:
    app: notesapp

spec:
  replicas: 2
  selector:
    matchLabels:
      app: notesapp
  template:
    metadata:
      labels:
        app: notesapp
    spec:
      containers:
        - name: notesapp-cont
          image: shivangsharma28/notes-app-k8s
          ports: 
            - containerPort: 8000